# permissions for end users to view secretproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretprovider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secrets-store-controller
    app.kubernetes.io/part-of: secrets-store-controller
    app.kubernetes.io/managed-by: kustomize
  name: secretprovider-viewer-role
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io.secrets-store.csi.x-k8s.io
  resources:
  - secretproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io.secrets-store.csi.x-k8s.io
  resources:
  - secretproviders/status
  verbs:
  - get
