apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProvider
metadata:
  name: secretprovider-azure
spec:
  serviceAccountName: sa
  secretProviderClassName: azure-linux
  rotationPollInterval: 2m
  tokenRequests:
  - audience: api://AzureADTokenExchange
