apiVersion: secrets-store.csi.x-k8s.io.secrets-store.csi.x-k8s.io/v1
kind: SecretProvider
metadata:
  labels:
    app.kubernetes.io/name: secretprovider
    app.kubernetes.io/instance: secretprovider-sample
    app.kubernetes.io/part-of: secrets-store-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secrets-store-controller
  name: secretprovider-sample
spec:
  # TODO(user): Add fields here
