apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-linux
spec:
  provider: azure
  secretObjects:
  - data:
    - key: foo
      objectName: secret1
    - key: bar
      objectName: secret2
    secretName: foosecret
    type: Opaque
  parameters:
    clientID: 47fb5768-24da-4940-a1c7-612c5b0846d3
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kindkv"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
          objectAlias: secret1
        - |
          objectName: secret2
          objectType: secret
          objectVersion: ""
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
